model:
  hidden_size: 960
  num_hidden_layers: 10
  use_moe: false
  vocab_size: 6400
  num_attention_heads: 10
  num_key_value_heads: 5

tokenizer_path: ../MiniMind/model
data_path: data/processed/sft_chat_mix.jsonl
init_checkpoint: checkpoints/pretrain_120m_960_2b.pth
output_checkpoint: checkpoints/sft_120m_960_chat.pth
resume_checkpoint: checkpoints/sft_120m_960_chat_resume.pth
log_path: outputs/sft_120m_loss.jsonl

training:
  stage: sft
  device: cuda
  dtype: float16
  batch_size: 1
  gradient_accumulation_steps: 32
  context_length: 1024
  learning_rate: 0.00002
  max_steps: 5000
  warmup_steps: 300
  save_steps: 500
  eval_steps: 250
  eval_batches: 8
  grad_clip: 1.0
  num_workers: 2
  seed: 121
